### PR TITLE
feat: Add cave location facet

### PR DESCRIPTION
**Pull request by askneller**
Add a `Facet` that represents the height of the floor of a cave if it is present. If no cave is present in the region a nonsensical value is used (currently `Float.NaN`).

### CODE REVIEW

**Review by Qwertygiy — APPROVED** [review]
Code looks good! I haven't had a chance to test it yet, as it would require something that can use or log the facet data, but the logic appears sound, the code style looks good, and I can think of quite a few use cases for this feature.

I also really appreciate the nice JavaDocs and explanatory comments; they make things much easier to understand at a glance. It's easy to get complacent and leave only basic remarks on relatively small and simple classes like these, so I just want to make sure that this good practice doesn't go unnoticed. :)

I do have one question/suggestion, however! A suqquestion, if you will. Why only the bottom, and not also the top? A CaveCeiling facet could be similarly useful (thinking particularly of stalactites & stalagmites being generated), or perhaps this could be changed to a CaveHeight facet, changing the facet to contain two values that are calculated in the same pass, one for the floor and one for the ceiling.

**Comment by askneller** [comment]
Hi @Qwertygiy  thanks very much for the comments, they're greatly appreciated.

You're right, a CaveCeiling facet would be a great idea. I'll start work on it as soon as I can. I'm not sure a CaveHeight would work in one pass as the ceiling and floor might be in different regions. But I can add one that is calculated after the other two.

For testing I'll add the code that I used the facet with. First it'll require me to make a PR into engine: I added an annotation that ensured that one rasterizer runs after another (my CaveFloor blocks were being overwritten by the cave itself :) ).

**Comment by askneller** [comment]
I added some classes that can be used for testing. `CaveObjectFacet`, `CaveObjectProvider`, `CaveObjectType`, `CaveObjectRasterizer`. As is if you create a game from CoreSampleGameplay and enable the Caves module, you should be able to find some caves with torches scattered around the floor.

Note that this relies on [https://github.com/MovingBlocks/Terasology/pull/3825](url).

E.g.
screenshot

**Comment by Qwertygiy** [comment]
Looks fantastic! 👍 The rasterizer ordering issue is something I have only considered academically before, but as I progress with my own worldgen development in GenericBiomes, I'm sure I'll be needing to use that feature, to prevent problems like trees being generated before lakes, cutting the ground out from beneath them and leaving them floating mid-air. 

In regards to the possibility of the ceiling and floor being in different regions, I don't think that would be too much of a problem, as long as that behavior is documented and expected. If the floor is found, but not the ceiling, the floor value would be legitimate and the ceiling value would be nonsensical. If the ceiling was found, but not the floor, the floor value would be nonsensical and the ceiling value would be legitimate. (If neither was found, wow, that's a big cave, but it could happen.)

The primary reason that I think it would be better to calculate both together than separately, is that the overhead of looping through most positions in a region *once* (since you wouldn't be able to break the y-loop when you found a floor or ceiling, in case you might find the other afterwards) would still be more efficient than looping through *partial* areas of the region *twice.* After all, there's no guarantee that a floor will be near the bottom of the region or that a ceiling will be near the top of the region.

I did just realize something, however. Is it not possible for there to be multiple caves within one region, so that there is more than one valid cave floor? As I recall, chunks are 32x16x32, and so there would definitely appear to be the potential for there to be one smaller cave near the bottom of the region, and the floor of another cave above it, if the cave generator doesn't prohibit such things somehow. If that's the case, it should not be too difficult to account for; it would likely just need to be changed to adding the floor height to a list, instead of setting the floor height and breaking the loop.

**Comment by askneller** [comment]
Oh yeah one loop would be better. And good point about multiple caves! 

What do you think about changing this to a `CaveLocationFacet` where each x/z combination provides a list of `CaveLocation` objects, each containing a `ceiling`, `floor`, and `height`?

**Comment by Qwertygiy** [comment]
If there is a good way to implement that, it would certainly benefit the rasterizers if they could quickly determine how much room they had to work with, even if the region didn't encompass the entire cave. Stalactites and stalagmites come to mind again, where you might want taller ones in taller caves which wouldn't fit in smaller caves. The issue then becomes, how does the *facet* know what the height is, if the region doesn't encompass the entire cave? It may be possible to determine this with the boundaries such as used in the TreeFacetProvider of Core, but I don't know how those are implemented and what their limits are.

It could still be accomplished by setting the value that extends beyond the region to the NaN value, so if you had the floor inside the region but not the ceiling, the floor would be valid and the ceiling would be NaN.

That's one reason why I think "height" shouldn't be saved to the facet, in addition to the fact that it would take a lot more memory and data to save an extra float value for each location in a cave, than it would take to just subtract the floor from ceiling when another provider or rasterizer needed that specific location.

**Comment by askneller** [comment]
Updated ```CaveFloorFacet``` to ```CaveLocationFacet```.

Testing should be the same (I updated the classes mentioned above to add to the floor and ceiling).

If you start a game with seed ```100``` and dig down from your starting location (x = 0, z = 0) you will find ```CaveLocation```s (ceiling -24, floor -32) and (ceiling -68, floor -77).

screenshot2

**Review by skaldarnar — APPROVED** [review]

**Pull request merged**
